### ISSUE TITLE
wrong number of arguments (2 for 0) error

### ISSUE THREAD

**Issue by maju6406** [puppetlabs/prosvcs-node_manager#51]
I'm using node_manager in a module I created (https://github.com/maju6406/pe_code_manager_easy_setup). When I try to install it using 'puppet module install' I get 'Error: Failed to apply catalog: wrong number of arguments (2 for 0)'. but if I run it again it works. When running with trace on it looks like this line causing the issue https://github.com/puppetlabs/prosvcs-node_manager/blob/master/lib/puppet/util/node_groups.rb#L32

Additional output here: 
https://gist.github.com/maju6406/bbdbb0355a84dc0cb0344855dd3905f5

Env:
Vagrant version: 1.9.0
Using Puppet Debugging Kit with pe-201652-master

**Comment by WhatsARanjit** [comment]
Taking a look at this, with @reidmv we applied:

```
begin
  require 'yaml'
  require 'puppetclassify'
  parent = PuppetClassify
rescue LoadError => e
  parent = Object
end
```

...to guard against issues where gems may not be loaded on an Agent (but yes on the Master), to continue on because the Agent doesn't need the libs, only the Master during compilation.  Unfortunately, during `puppet apply`, it's the same headspace.  So when we get to:

```
https://github.com/puppetlabs/prosvcs-node_manager/blob/master/lib/puppet/util/node_groups.rb#L32
```

...we are super'ing to a dummy `Object` which takes no args.  So we end up supplying 2 args to something that take 0 args.  I tried putting some logic into only supply args if the parent is `PuppetClassify`, but then the rest of the code doesn't know required methods like `groups` to continue on.  The reason being the puppetclassify libs aren't actually loaded yet.

**Comment by TraGicCode** [comment]
i'm having the same issue as the orig poster

**Comment by WhatsARanjit** [comment]
@TraGicCode It's hard to create a class with a parent that hasn't been installed yet.  What I mean is the `PuppetClassify` class is not yet installed and `Puppet::Util::Node_groups` is read in when the catalog is first compiled.  We faked it with Reid's code above.  This is good for Master/Agent things, but for `puppet apply`, the Agent messes up.

I have a proposed fix in the works here: https://github.com/WhatsARanjit/prosvcs-node_manager/blob/issue-51/lib/puppet/provider/node_group/puppetclassify.rb#L9
...using `load` to do it in runtime, rather than when code is read in initially.  This will delay reading the `util` until after the `feature` confine allows the provider to be used.

Kind of an odd thing to do so I'm not sure what the implications are.  My other idea is to remove the `puppetclassify` dependency all together.

**Comment by WhatsARanjit** [comment]
@TraGicCode I uploaded a new release this morning with an `https` provider to avoid these types of issues.  Please try it out and give me feedback.  Thanks.

**Comment by TraGicCode** [comment]
Thanks for the quick response. I'll give it a shot monday morning



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------
